name: Android CI

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"
  workflow_dispatch:
    inputs:
      buildType:
        description: "What brunch to run?"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit tests
        run: ./gradlew test

      - name: Build Apk/AAB
        run: |
          if [ "${{ github.event.inputs.buildType }}" == "release" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

      - name: Upload APK/AAB as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ github.event.inputs.buildType }}
          path: |
            app/build/outputs/**/*.apk
            app/build/outputs/**/*.aab